version: '3.6'
services:
  genesis:
    image: besu
    network_mode: host
    ports:
      - "8545:8545" # JSON-RPC
      - "8546:8546" # WebSockets
      - "8547:8547" # GraphQL
      - "8550:8550" # HTTP ENGINE JSON-RPC
      - "8551:8551" # WS ENGINE JSON-RPC
      - "30303:30303" # P2P
    volumes:
      - ./data:/opt/besu/data
    command:
      [
        "--identity=genesis",
        "--data-path=/opt/besu/data/node0/data",
        "--genesis-file=/opt/besu/data/cliqueGenesis.json",
        "--rpc-http-enabled=true",
        "--graphql-http-enabled=true",
        "--rpc-http-api=ETH,NET,CLIQUE,ADMIN",
        "--host-allowlist=*",
        "--rpc-http-cors-origins=all",
        "--nat-method=DOCKER"
      ]

  node1:
    depends_on:
      - genesis
    image: node
    network_mode: host
    entrypoint: [ "./data/scripts/enode.sh" ]
    ports:
      - "8548:8545" # JSON-RPC
      - "8549:8546" # WebSockets
      - "8552:8550" # HTTP ENGINE JSON-RPC
      - "8553:8551" # WS ENGINE JSON-RPC
      - "30304:30303" # P2P
    volumes:
      - ./data:/opt/besu/data
    command:
      [
        "--identity=node1",
        "--data-path=/opt/besu/data/node1/data",
        "--genesis-file=/opt/besu/data/cliqueGenesis.json",
        "--rpc-http-enabled=true",
        "--rpc-http-api=ETH,NET,CLIQUE",
        "--host-allowlist=*",
        "--rpc-http-cors-origins=all",
        "--p2p-port=30304",
        "--rpc-http-port=8548",
        "--nat-method=DOCKER"
      ]

  node2:
    depends_on:
      - genesis
    image: node
    network_mode: host
    entrypoint: [ "./data/scripts/enode.sh" ]
    ports:
      - "8554:8545" # JSON-RPC
      - "8555:8546" # WebSockets
      - "8556:8550" # HTTP ENGINE JSON-RPC
      - "8557:8551" # WS ENGINE JSON-RPC
      - "30305:30303" # P2P
    volumes:
      - ./data:/opt/besu/data
    command:
      [
        "--identity=node2",
        "--data-path=/opt/besu/data/node2/data",
        "--genesis-file=/opt/besu/data/cliqueGenesis.json",
        "--rpc-http-enabled=true",
        "--rpc-http-api=ETH,NET,CLIQUE",
        "--host-allowlist=*",
        "--rpc-http-cors-origins=all",
        "--p2p-port=30305",
        "--rpc-http-port=8554",
        "--nat-method=DOCKER"
      ]

  node3:
    depends_on:
      - genesis
    image: node
    network_mode: host
    entrypoint: [ "./data/scripts/enode.sh" ]
    ports:
      - "8558:8545" # JSON-RPC
      - "8559:8546" # WebSockets
      - "8560:8550" # HTTP ENGINE JSON-RPC
      - "8561:8551" # WS ENGINE JSON-RPC
      - "30306:30303" # P2P
    volumes:
      - ./data:/opt/besu/data
    command:
      [
        "--identity=node3",
        "--data-path=/opt/besu/data/node3/data",
        "--genesis-file=/opt/besu/data/cliqueGenesis.json",
        "--rpc-http-enabled=true",
        "--rpc-http-api=ETH,NET,CLIQUE",
        "--host-allowlist=*",
        "--rpc-http-cors-origins=all",
        "--p2p-port=30306",
        "--rpc-http-port=8558",
        "--nat-method=DOCKER"
      ]
