version: '3.6'
services:
  bootnode-001-genesis:
    restart: on-failure
    image: genesis-v2
    network_mode: host
    volumes:
      - ./besu:/opt/besu
      - ./data:/opt/besu/data
    command:
      [
        "--identity=genesis",
        "--data-path=/opt/besu/data/node0/data",
        "--genesis-file=/opt/besu/data/cliqueGenesis.json",
        "--rpc-http-enabled=true",
        "--graphql-http-enabled=true",
        "--rpc-http-api=ETH,NET,CLIQUE,ADMIN",
        "--host-allowlist=*",
        "--rpc-http-cors-origins=all",
        "--nat-method=DOCKER"
      ]

  bootnode-002-initial-signer-001:
    restart: on-failure
    depends_on:
      - bootnode-001-genesis
    image: node-v2
    network_mode: host
    entrypoint: [ "./data/scripts/enode.sh" ]
    volumes:
      - ./besu:/opt/besu
      - ./data:/opt/besu/data
    command:
      [
        "--identity=bootnode-002-initial-signer-001",
        "--data-path=/opt/besu/data/node1/data",
        "--genesis-file=/opt/besu/data/cliqueGenesis.json",
        "--rpc-http-enabled=true",
        "--rpc-http-api=ETH,NET,CLIQUE,ADMIN",
        "--host-allowlist=*",
        "--rpc-http-cors-origins=all",
        "--p2p-port=30313", # 30303 + 10
        "--rpc-http-port=8555", # 8545 + 10
        "--nat-method=DOCKER"
      ]

  initial-signer-002:
    restart: on-failure
    depends_on:
      - bootnode-001-genesis
      - bootnode-002-initial-signer-001
    image: node-v2
    network_mode: host
    entrypoint: [ "./data/scripts/nodes.sh" ]
    volumes:
      - ./besu:/opt/besu
      - ./data:/opt/besu/data
    command:
      [
        "--identity=initial-signer-002",
        "--data-path=/opt/besu/data/node2/data",
        "--genesis-file=/opt/besu/data/cliqueGenesis.json",
        "--rpc-http-enabled=true",
        "--rpc-http-api=ETH,NET,CLIQUE",
        "--host-allowlist=*",
        "--rpc-http-cors-origins=all",
        "--p2p-port=30323", # 30313 + 10
        "--rpc-http-port=8565", # 8555 + 10
        "--nat-method=DOCKER"
      ]

  node-001:
    restart: on-failure
    depends_on:
      - bootnode-001-genesis
      - bootnode-002-initial-signer-001
    image: node-v2
    network_mode: host
    entrypoint: [ "./data/scripts/nodes.sh" ]
    volumes:
      - ./besu:/opt/besu
      - ./data:/opt/besu/data
    command:
      [
        "--identity=node-001",
        "--data-path=/opt/besu/data/node3/data",
        "--genesis-file=/opt/besu/data/cliqueGenesis.json",
        "--rpc-http-enabled=true",
        "--rpc-http-api=ETH,NET,CLIQUE",
        "--host-allowlist=*",
        "--rpc-http-cors-origins=all",
        "--p2p-port=30333", # 30323 + 10
        "--rpc-http-port=8575", # 8565 + 10
        "--nat-method=DOCKER"
      ]

  node-002:
    restart: on-failure
    depends_on:
      - bootnode-001-genesis
      - bootnode-002-initial-signer-001
    image: node-v2
    network_mode: host
    entrypoint: [ "./data/scripts/nodes.sh" ]
    volumes:
      - ./besu:/opt/besu
      - ./data:/opt/besu/data
    command:
      [
        "--identity=node-002",
        "--data-path=/opt/besu/data/node4/data",
        "--genesis-file=/opt/besu/data/cliqueGenesis.json",
        "--rpc-http-enabled=true",
        "--rpc-http-api=ETH,NET,CLIQUE",
        "--host-allowlist=*",
        "--rpc-http-cors-origins=all",
        "--p2p-port=30343", # 30333 + 10
        "--rpc-http-port=8585", # 8575 + 10
        "--nat-method=DOCKER"
      ]

  node-003:
    restart: on-failure
    depends_on:
      - bootnode-001-genesis
      - bootnode-002-initial-signer-001
    image: node-v2
    network_mode: host
    entrypoint: [ "./data/scripts/nodes.sh" ]
    volumes:
      - ./besu:/opt/besu
      - ./data:/opt/besu/data
    command:
      [
        "--identity=node-003",
        "--data-path=/opt/besu/data/node5/data",
        "--genesis-file=/opt/besu/data/cliqueGenesis.json",
        "--rpc-http-enabled=true",
        "--rpc-http-api=ETH,NET,CLIQUE",
        "--host-allowlist=*",
        "--rpc-http-cors-origins=all",
        "--p2p-port=30353", # 30343 + 10
        "--rpc-http-port=8595", # 8585 + 10
        "--nat-method=DOCKER"
      ]
